### ISSUE TITLE
Set CircleCI config to only deploy from tags

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando-messaging#27]
The CircleCI config is running the `deploy` job for the master branch and the build job for tags. 

https://github.com/Duke-GCB/lando-messaging/blob/19408ecfc77994ee5e27e37d9507d7776ae85389/.circleci/config.yml#L61-L77
Unless there's a strong reason otherwise, we should adjust this to 

1. Build (test) all branches/releases
2. Deploy all releases

Example from lando - https://github.com/Duke-GCB/lando/blob/6623b5f1f8713b87320f1d2858781047c487f2e7/.circleci/config.yml#L70-L85

**Comment by dleehr** [comment]
@johnbradley do you recall if this was intentional?

**Comment by johnbradley** [comment]
> do you recall if this was intentional?

I don't think so.
